# Generated by Django 4.2.16 on 2024-09-15 08:46

from django.db import migrations

def insert_dummy_data(apps, schema_editor):
    Document = apps.get_model('server', 'Document')
    
    # Insert dummy data
    Document.objects.create(name="Document 1", document_path="sample_pdfs/example_1/example_1.pdf", output_path="server/temp_data/example_1/example_1_output.json")
    Document.objects.create(name="Document 2", document_path="sample_pdfs/example_2/example_2.pdf", output_path="server/temp_data/example_2/example_2_output.json")
    Document.objects.create(name="Document 3", document_path="sample_pdfs/example_3/example_3.pdf", output_path="server/temp_data/example_3/example_3_output.json")


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_dummy_data),
    ]
